MESSAGE(STATUS "make for MacOS")
SET(CMAKE_SYSTEM_NAME Darwin)
SET(CMAKE_SYSTEM_VERSION 1)
SET(CMAKE_SYSTEM_PROCESSOR amd64)
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

ADD_DEFINITIONS(-Wno-multichar)
ADD_DEFINITIONS(-Wno-pointer-to-int-cast)

# release, macos only linked by O2 & O3
ADD_DEFINITIONS(-O2)

# debug
ADD_DEFINITIONS(-g)
ADD_DEFINITIONS(-fPIC)
ADD_DEFINITIONS(-std=c99)
